// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANnxaXUis5-SlnVolVUkpXmoPkJ_cKY-Y',
    appId: '1:263861833737:web:14ccf5265db976b6e2e8d8',
    messagingSenderId: '263861833737',
    projectId: 'quizapp-ec25a',
    authDomain: 'quizapp-ec25a.firebaseapp.com',
    databaseURL: 'https://quizapp-ec25a-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-ec25a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALxjEopZHikG3E--LaDyKNTwwN_dTYQ3s',
    appId: '1:263861833737:android:3dbd15e6f91d0582e2e8d8',
    messagingSenderId: '263861833737',
    projectId: 'quizapp-ec25a',
    databaseURL: 'https://quizapp-ec25a-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-ec25a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2PPd3egUTzlxlM4SX_BlSZh9jrG7r0Fo',
    appId: '1:263861833737:ios:a5c47332326cf136e2e8d8',
    messagingSenderId: '263861833737',
    projectId: 'quizapp-ec25a',
    databaseURL: 'https://quizapp-ec25a-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-ec25a.appspot.com',
    iosBundleId: 'com.example.flyhigh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2PPd3egUTzlxlM4SX_BlSZh9jrG7r0Fo',
    appId: '1:263861833737:ios:f51500bd60b41505e2e8d8',
    messagingSenderId: '263861833737',
    projectId: 'quizapp-ec25a',
    databaseURL: 'https://quizapp-ec25a-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-ec25a.appspot.com',
    iosBundleId: 'com.example.flyhigh.RunnerTests',
  );
}
